security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # utilisé pour recharger l'utilisateur depuis la session & autres fonctionnalités
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur # class utilisateur
                property: email # identification de l'utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/ # pour les outils de dev
            security: false
        main: # pare-feu pour l'app
            lazy: true
            provider: app_user_provider # fournisseur d'utilisateurs
            custom_authenticator: App\Security\AppAuthenticator # système de connexion
            logout:
                path: app_logout # se déconnecter
                target: app_login # redirection vers la page de connexion après déconnexion

            remember_me: # "se souvenir de moi"
                secret: '%kernel.secret%' # clé secrète 
                lifetime: 604800 # durée de validité 
                path: /
                #always_remember_me: true # "se souvenir de moi"

    # contrôle d'accès pour les sections du site
    # la première règle qui correspond est utilisée
    access_control:
        # page /login doit être accessible par tt le monde (même non connecté)
        - { path: ^/login, roles: PUBLIC_ACCESS }

         # gestion des tickets par l'admin
        - { path: ^/admin/ticket, roles: ROLE_ADMIN }

          # gestion des utilisateurs réservée à l'admin
        - { path: ^/utilisateur, roles: ROLE_ADMIN }

        # pages de gestion des catégories (/categorie, /categorie/new, etc.)
        # nécessitent le rôle ROLE_ADMIN
        - { path: ^/categorie, roles: ROLE_ADMIN }

        # pages de gestion des statuts 
        - { path: ^/statut, roles: ROLE_ADMIN }

        # page /home (accueil après connexion) nécessite d'être connecté (ROLE_USER)
        # ROLE_USER est donné à ts les utilisateurs authentifiés
        - { path: ^/home, roles: ROLE_USER }

        # section des tickets, accessible publiquement 
        - { path: ^/ticket, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
